### ISSUE TITLE
License for text and images maybe added as CC-type

### ISSUE THREAD

**Issue by arcturusannamalai** [mrdougwright/RubyKin#2]
Hello Doug:
Thanks for sharing the source of the book and illustrations. I'm now translating this book into Indian language Tamil for kids to learn Ruby from that way.

For this work to be fully valuable I would request you to add a CC-class license (CC by SA, CC NC etc) for the contents and illustration.

Sincerely,
-Muthu

**Comment by mrdougwright** [comment]
Hi Muthu,

Sorry for the delay. CC license added. And you are free to translate and use commercially.
Please email me with any future questions concerns: mrdougwright [at>] gmail

**Comment by arcturusannamalai** [comment]
Hi Doug,
Thanks so much! I will update you once we are complete.
I will also be using the CC license; my email is ezhillang [at>] gmail.

Best Regards
